In [6]:
import pandas as pd

homelessness = pd.read_csv("2013 US State Statistics.csv")

homelessness.info()
homelessness.head()
homelessness.shape
homelessness.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 15 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   State                                                     54 non-null     object
 1   Total Homeless Persons                                    54 non-null     object
 2   Rate of Homeless Population per 10,000                    54 non-null     float64
 3   Chronic individuals (% Homeless population)               54 non-null     object
 4   Chronic Persons in Families (% Homeless population)       54 non-null     object
 5   Chronic Homeless Persons, Total (% Homeless population)   54 non-null     object
 6   Persons in families (% Homeless population)               54 non-null     object
 7   Unaccompanied Children and youth (% Homeless population)  54 non-null     object
 8   Veterans (% Homeless population)                          54 non-null     object
 9   Unsheltered persons (% Homeless population)               54 non-null     object
 10  Change from Last Year                                     54 non-null     object
 11  Population                                                54 non-null     int64
 12  Source for population                                     54 non-null     object
 13  Source for Homeless Statistics                            54 non-null     object
 14  Notes on Population                                       2 non-null      object
dtypes: float64(1), int64(1), object(13)
memory usage: 6.5+ KB

       Rate of Homeless Population per 10,000    Population
count                               54.000000  5.400000e+01
mean                                20.097407  5.926105e+06
std                                 17.325706  6.937630e+06
min                                  8.030000  1.064050e+05
25%                                 11.300000  1.456074e+06
50%                                 13.505000  3.890316e+06
75%                                 23.077500  6.676274e+06
max                                106.200000  3.833252e+07

In [9]:
homelessness.values  # A two-dimensional NumPy array of values.
homelessness.columns
homelessness.index

RangeIndex(start=0, stop=54, step=1)

# Sorting rows
homelessness.sort_values("population")

In [16]:
homelessness.sort_values("Population", ascending=False).head()

,State,Total Homeless Persons,"Rate of Homeless Population per 10,000",Chronic individuals (% Homeless population),Chronic Persons in Families (% Homeless population),"Chronic Homeless Persons, Total (% Homeless population)",Persons in families (% Homeless population),Unaccompanied Children and youth (% Homeless population),Veterans (% Homeless population),Unsheltered persons (% Homeless population),Change from Last Year,Population,Source for population,Source for Homeless Statistics,Notes on Population
4,California,136826,35.69,25.9%,2.8%,28.7%,18.3%,11.3%,11.1%,66.7%,4.53%,38332521,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
45,Texas,29615,11.20,16.1%,2.6%,18.7%,29.9%,7.0%,13.1%,40.8%,-13.03%,26448193,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
33,New York,77430,39.40,5.2%,2.9%,8.2%,59.7%,4.7%,6.0%,5.4%,11.30%,19651127,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
9,Florida,47862,24.48,16.3%,3.9%,20.2%,34.5%,7.2%,11.5%,58.9%,-13.25%,19552860,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
14,Illinois,13425,10.42,10.5%,1.3%,11.7%,40.7%,7.9%,9.4%,16.4%,-5.08%,12882135,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN

In [20]:
homelessness.sort_values("State", ascending=False).head()[["State", "Population"]]

            State  Population
53        Wyoming      582658
52      Wisconsin     5742713
51  West Virginia     1854304
50     Washington     6971406
49       Virginia     8260405

In [26]:
# subsetting cols
homelessness["State"]
homelessness.State
homelessness[["State", "Population"]].head()

        State  Population
0     Alabama     4833722
1      Alaska      735132
2     Arizona     6626624
3    Arkansas     2959373
4  California    38332521

In [43]:
# Subsetting rows
# the idea is that homelessness["Population"] > 5742713 return a boolean column value(True | False), and by defaulte
# homelessness[bool_val] display rows that just have True value

homelessness[homelessness["Population"] > 5742713]
homelessness[homelessness.State == "Arizona"]
homelessness[(homelessness.Population > 5742713) & (homelessness.Population < 8742713)].head()

,State,Total Homeless Persons,"Rate of Homeless Population per 10,000",Chronic individuals (% Homeless population),Chronic Persons in Families (% Homeless population),"Chronic Homeless Persons, Total (% Homeless population)",Persons in families (% Homeless population),Unaccompanied Children and youth (% Homeless population),Veterans (% Homeless population),Unsheltered persons (% Homeless population),Change from Last Year,Population,Source for population,Source for Homeless Statistics,Notes on Population
2,Arizona,10562,15.94,10.1%,1.2%,11.2%,38.4%,6.4%,11.6%,29.6%,-6.55%,6626624,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN

In [45]:
# subsetting rows by categories
canu = ["California", "Arizona", "Nevada", "Utah"]
homelessness[homelessness.State.isin(canu)]

,State,Total Homeless Persons,"Rate of Homeless Population per 10,000",Chronic individuals (% Homeless population),Chronic Persons in Families (% Homeless population),"Chronic Homeless Persons, Total (% Homeless population)",Persons in families (% Homeless population),Unaccompanied Children and youth (% Homeless population),Veterans (% Homeless population),Unsheltered persons (% Homeless population),Change from Last Year,Population,Source for population,Source for Homeless Statistics,Notes on Population
2,Arizona,10562,15.94,10.1%,1.2%,11.2%,38.4%,6.4%,11.6%,29.6%,-6.55%,6626624,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
4,California,136826,35.69,25.9%,2.8%,28.7%,18.3%,11.3%,11.1%,66.7%,4.53%,38332521,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
29,Nevada,8443,30.26,10.5%,0.1%,10.5%,10.0%,22.8%,11.3%,56.2%,-14.94%,2790136,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN
47,Utah,3277,11.30,10.6%,3.3%,13.9%,40.2%,4.3%,10.0%,12.8%,-7.09%,2900872,http://en.wikipedia.org/wiki/List_of_U.S._stat...,http://b.3cdn.net/naeh/d1b106237807ab260f_qam6...,NaN